### ISSUE TITLE
"Missing from JS" results says JS is missing "functions"

### ISSUE THREAD

**Issue by dfabulich** [StateOfJS/StateOfJS-2020#51]
According to https://2020.stateofjs.com/en-US/opinions/#missing_from_js the 5th most popular answer to the "What do you feel is currently missing from JavaScript?" question is, "functions"

… that can't be right, can it??

When I view the raw data, the bucket for "functions" looks buggy:

```json
{
    "id": "functions",
    "count": 154,
    "percentage": 8.2,
    "entity": {
    "id": null,
    "homepage": null,
    "name": null
    }
},
```

Unlike all the other buckets, "functions" has null `id` and no `name`. I think something bad has happened to the data here.

**Comment by SachaG** [comment]
Like I said on Discord I now remember that this happened because the list of regexp used to normalize the "what's missing from CSS" question was mistakenly expanded to normalize the "what's missing from JS" question without considering how the existing CSS regexps would affect the JS results. 

I'll fix it by establishing two separate lists for that section of the normalization rules.
